# Generated by Django 4.1.13 on 2024-04-30 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_ID', models.IntegerField(db_column='student ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='student name', max_length=100)),
            ],
            options={
                'db_table': 'Student',
                'managed': True,
            },
        ),
    ]
