# Generated by Django 4.1.13 on 2024-05-02 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_address_student_birthdate_student_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(db_column='student_name', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_ID',
            field=models.IntegerField(db_column='student_ID', primary_key=True, serialize=False),
        ),
    ]
